/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package vista;

import java.awt.CardLayout;

/**
 *
 * @author Estudiante
 */
public class PnlPrincipal extends javax.swing.JPanel {
    
    private JframePrincipal frm;

    public void setFrm(JframePrincipal frm) {
        this.frm = frm;
    }
    
    
    
    /**
     * Creates new form PnlPrincipal
     */
    public PnlPrincipal() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton3 = new javax.swing.JButton();
        Norte = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        Centro = new javax.swing.JPanel();
        BtnCrear_prueba = new javax.swing.JButton();
        BtnCalificar_prueba = new javax.swing.JButton();

        jButton3.setText("jButton3");

        jLabel1.setText("SELECCIONE UNA OPCION");
        Norte.add(jLabel1);

        BtnCrear_prueba.setText("Crear Prueba");
        BtnCrear_prueba.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnCrear_pruebaActionPerformed(evt);
            }
        });

        BtnCalificar_prueba.setText("Calificar Prueba");
        BtnCalificar_prueba.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnCalificar_pruebaActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout CentroLayout = new javax.swing.GroupLayout(Centro);
        Centro.setLayout(CentroLayout);
        CentroLayout.setHorizontalGroup(
            CentroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(CentroLayout.createSequentialGroup()
                .addContainerGap(114, Short.MAX_VALUE)
                .addComponent(BtnCrear_prueba, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(BtnCalificar_prueba, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(136, Short.MAX_VALUE))
        );
        CentroLayout.setVerticalGroup(
            CentroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(CentroLayout.createSequentialGroup()
                .addGap(57, 57, 57)
                .addGroup(CentroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(BtnCalificar_prueba)
                    .addComponent(BtnCrear_prueba))
                .addContainerGap(103, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(Norte, javax.swing.GroupLayout.PREFERRED_SIZE, 480, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addComponent(Centro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(Norte, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(Centro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        Norte.getAccessibleContext().setAccessibleName("Aplicacion Profesor");
    }// </editor-fold>//GEN-END:initComponents

    private void BtnCalificar_pruebaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnCalificar_pruebaActionPerformed
        // TODO add your handling code here:
        //frm.cambiar_tarjeta("");
    }//GEN-LAST:event_BtnCalificar_pruebaActionPerformed

    private void BtnCrear_pruebaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnCrear_pruebaActionPerformed
        // TODO add your handling code here:
        //((CardLayout)PnlGeneral.getLayout()).show(PnlGeneral, "");
        frm.cambiar_tarjeta("prueba");

    }//GEN-LAST:event_BtnCrear_pruebaActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BtnCalificar_prueba;
    private javax.swing.JButton BtnCrear_prueba;
    private javax.swing.JPanel Centro;
    private javax.swing.JPanel Norte;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel1;
    // End of variables declaration//GEN-END:variables
}
